# Generated by Django 4.2.5 on 2023-11-03 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaEmb', '0002_alter_persona_pemb_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona_pemb',
            options={'permissions': [('can_view_persona', 'Can view persona_p emb'), ('can_add_persona', 'Can add persona_p emb'), ('can_change_persona', 'Can change persona_p emb'), ('can_delete_persona', 'Can delete persona_p emb')]},
        ),
    ]
