# Generated by Django 4.2.5 on 2023-11-03 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaEmb', '0003_alter_persona_pemb_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultado_per_pemb',
            options={'permissions': [('can_change_res_per', 'Can change resultado_per_p emb')]},
        ),
    ]
