# Generated by Django 4.2.5 on 2023-09-16 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('idInstitucion', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombreInstitucion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('numero_de_muestra', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('direccion', models.TextField()),
                ('expediente', models.CharField(max_length=50)),
                ('resultado', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('institucion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VPH.institucion')),
            ],
        ),
    ]
