# Generated by Django 4.2.5 on 2023-09-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VPH', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='dui',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
