# Generated by Django 4.2.5 on 2023-09-22 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VPH', '0002_persona_dui'),
    ]

    operations = [
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id_dep', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombreDep', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='resultado',
            fields=[
                ('id_res', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('resultado', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='persona',
            name='resultado',
        ),
        migrations.CreateModel(
            name='resultado_per',
            fields=[
                ('id_res_per', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('id_res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VPH.resultado')),
                ('numero_de_muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VPH.persona')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='id_dep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VPH.departamento'),
            preserve_default=False,
        ),
    ]
