# Generated by Django 4.2.5 on 2023-09-26 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VPH', '0003_departamento_resultado_remove_persona_resultado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='id_dep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VPH.departamento'),
        ),
    ]
