# Generated by Django 4.2.5 on 2023-11-02 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VPH', '0006_alter_persona_fecha_alter_persona_id_dep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'permissions': [('view_Persona', 'Can view Persona'), ('change_Persona', 'Can change Persona'), ('add_Persona', 'Can add Persona'), ('delete_Persona', 'Can delete Persona')]},
        ),
    ]
