# Generated by Django 4.2.5 on 2023-11-02 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VPH', '0007_alter_persona_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'permissions': [('view_Persona', 'Can view persona'), ('change_Persona', 'Can change persona'), ('add_Persona', 'Can add persona'), ('delete_Persona', 'Can delete persona')]},
        ),
    ]
