# Generated by Django 4.2.5 on 2023-11-02 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VPH', '0009_alter_persona_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={},
        ),
    ]
