# Generated by Django 4.2.5 on 2023-10-23 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departamento_tbs',
            fields=[
                ('id_dep', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombreDep', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion_tbs',
            fields=[
                ('idInstitucion', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombreInstitucion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona_TBS',
            fields=[
                ('numero_de_muestra', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('direccion', models.TextField()),
                ('dui', models.CharField(max_length=50)),
                ('expediente', models.CharField(max_length=50)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('id_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TBS.departamento_tbs')),
                ('institucion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TBS.institucion_tbs')),
            ],
        ),
        migrations.CreateModel(
            name='resultado_tbs',
            fields=[
                ('id_res', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('resultado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='resultado_per_tbs',
            fields=[
                ('id_res_per', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('id_res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TBS.resultado_tbs')),
                ('numero_de_muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TBS.persona_tbs')),
            ],
        ),
    ]
