# Generated by Django 4.2.5 on 2023-11-03 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TBS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona_tbs',
            options={'permissions': [('can_view_persona', 'Can view persona'), ('can_add_persona', 'Can add persona'), ('can_change_persona', 'Can change persona'), ('can_delete_persona', 'Can delete persona')]},
        ),
    ]
