# Generated by Django 4.2.5 on 2023-11-03 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TBS', '0002_alter_persona_tbs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona_tbs',
            options={'permissions': [('can_view_persona', 'Can view persona_tbs'), ('can_add_persona', 'Can add persona_tbs'), ('can_change_persona', 'Can change persona_tbs'), ('can_delete_persona', 'Can delete persona_tbs')]},
        ),
    ]
