# Generated by Django 4.2.5 on 2023-11-03 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VIH', '0002_alter_persona_vih_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona_vih',
            options={'permissions': [('can_view_persona', 'Can view persona_vih'), ('can_add_persona', 'Can add persona_vih'), ('can_change_persona', 'Can change persona_vih'), ('can_delete_persona', 'Can delete persona_vih')]},
        ),
    ]
